[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dashqt"
version = "0.0.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
include = ["dashqt*"]
